<?xml version="1.0" encoding="UTF-8"?><testrun name="TestPersoanaCorrectTest" project="Seminar_Persoana_Teste" tests="7" started="7" failures="0" errors="1" ignored="0">
  <testsuite name="tests.TestPersoanaCorrectTest" time="0.0">
    <testcase name="testCheckCNPConformance" classname="tests.TestPersoanaCorrectTest" time="0.0"/>
    <testcase name="testCheckCNPConformanceChar" classname="tests.TestPersoanaCorrectTest" time="0.0"/>
    <testcase name="testCheckCNPIncorrectFormat" classname="tests.TestPersoanaCorrectTest" time="0.0"/>
    <testcase name="testCheckCNPCorrectFormat" classname="tests.TestPersoanaCorrectTest" time="0.0"/>
    <testcase name="checkCNPNull" classname="tests.TestPersoanaCorrectTest" time="0.0">
      <error>java.lang.Exception: Unexpected exception, expected&lt;java.lang.IllegalArgumentException&gt; but was&lt;java.lang.NullPointerException&gt;&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)&#13;
Caused by: java.lang.NullPointerException&#13;
	at clase.Persoana.checkCNP(Persoana.java:62)&#13;
	at tests.TestPersoanaCorrectTest.checkCNPNull(TestPersoanaCorrectTest.java:65)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)&#13;
	... 15 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="checkOrderVarsta" classname="tests.TestPersoanaCorrectTest" time="0.0"/>
    <testcase name="testCheckCNPConformanceFirstChar" classname="tests.TestPersoanaCorrectTest" time="0.0"/>
  </testsuite>
</testrun>
